/* auth */
export const SET_UPDATE_POPUP = "SET_UPDATE_POPUP";
export const SET_PUSH_TOKEN = "SET_PUSH_TOKEN";
export const SET_LOCATION = "SET_LOCATION";
export const SET_PREVIEW = "SET_PREVIEW";
export const SET_USER_STORE = "SET_USER_STORE";
export const SET_USER_INFO = "SET_USER_INFO";
export const SET_AGREED_STATUS = "SET_AGREED_STATUS";
export const SET_IS_JOIN = "SET_IS_JOIN";
export const SET_DID_TRY_AL = "SET_DID_TRY_AL";
export const WITHDRAWAL = "WITHDRAWAL";
export const SET_CI = "SET_CI";
export const SET_IS_UPDATED = "SET_IS_UPDATED";
export const SET_PUSH_CNT = "SET_PUSH_CNT";
export const SET_WISH_CNT = "SET_WISH_CNT";

/* branches */
export const SET_ADDRESS1 = "SET_ADDRESS1";
export const SET_ADDRESS2 = "SET_ADDRESS2";
export const SET_BRANCHES = "SET_BRANCHES";
export const SET_BRANCHES_MORE = "SET_BRANCHES_MORE";
export const SET_BRANCH = "SET_BRANCH";
export const SET_STORE_MARK = "SET_STORE_MARK";

/* common */
export const SET_BOTTOM_NAVIGATION = "SET_BOTTOM_NAVIGATION";
export const SET_IS_STORE_POPUP = "SET_IS_STORE_POPUP";
export const SET_IS_APP_POPUP = "SET_IS_APP_POPUP";
export const SET_ALERT = "SET_ALERT";
export const SET_IS_LOADING = "SET_IS_LOADING";
export const SET_HEADER_HEIGHT = "SET_HEADER_HEIGHT";
export const SET_DID_TRY_POPUP = "SET_DID_TRY_POPUP";
export const SET_NOTIFICATION = "SET_NOTIFICATION";
export const SET_BRIGHTNESS = "SET_BRIGHTNESS";
export const SET_LINK = "SET_LINK";

/* coupon */
export const SET_COUPON_A = "SET_COUPON_A";
export const SET_COUPON = "SET_COUPON";
export const SET_MY_COUPON_A = "SET_MY_COUPON_A";
export const SET_MY_COUPON = "SET_MY_COUPON";
export const SET_COUPON_MORE = "SET_COUPON_MORE";
export const SET_MY_COUPON_MORE = "SET_MY_COUPON_MORE";
export const SET_COUPON_DETAIL = "SET_COUPON_DETAIL";

/* event */
export const SET_EVENT = "SET_EVENT";
export const SET_MY_EVENT = "SET_MY_EVENT";
export const SET_EVENT_MORE = "SET_EVENT_MORE";
export const SET_MY_EVENT_MORE = "SET_MY_EVENT_MORE";
export const SET_EVENT_DETAIL = "SET_EVENT_DETAIL";
export const SET_STAMP_HISTORY = "SET_STAMP_HISTORY";
export const SET_STAMP_HISTORY_MORE = "SET_STAMP_HISTORY_MORE";

/* exclusive */
export const SET_EXCLUSIVE = "SET_EXCLUSIVE";
export const SET_EXCLUSIVE_MORE = "SET_EXCLUSIVE_MORE";
export const SET_EXCLUSIVE_DETAIL = "SET_EXCLUSIVE_DETAIL";

/* exhibition */
export const SET_EXHIBITION = "SET_EXHIBITION";
export const SET_EXHIBITION_MORE = "SET_EXHIBITION_MORE";
export const SET_EXHIBITION_DETAIL = "SET_EXHIBITION_DETAIL";

/* flyer */
export const SET_LEAFLET = "SET_LEAFLET";
export const SET_LEAFLET_DETAIL = "SET_LEAFLET_DETAIL";
export const SET_PRODUCT = "SET_PRODUCT";
export const SET_PRODUCT_MORE = "SET_PRODUCT_MORE";
export const SET_SEARCHED_PRODUCT = "SET_SEARCHED_PRODUCT";
export const SET_SEARCHED_PRODUCT_MORE = "SET_SEARCHED_PRODUCT_MORE";
export const SET_PRODUCT_DETAIL = "SET_PRODUCT_DETAIL";
export const SET_CAROUSEL = "SET_CAROUSEL";

/* wish */
export const SET_WISH_ITEM = "SET_WISH_ITEM";
export const SET_WISH_ITEM_MORE = "SET_WISH_ITEM_MORE";

/* home */
export const SET_HOME_BANNER = "SET_HOME_BANNER";
export const SET_HOME_NOTICE = "SET_HOME_NOTICE";
export const SET_HOME_NOTICE_MORE = "SET_HOME_NOTICE_MORE";
export const SET_HOME_PRODUCTS = "SET_HOME_PRODUCTS";
export const SET_HOME_PRODUCTS_MORE = "SET_HOME_PRODUCTS_MORE";
export const SET_HOME_NARO = "SET_HOME_NARO";
export const SET_STORE_POPUP = "SET_STORE_POPUP";
export const SET_APP_POPUP = "SET_APP_POPUP";
